name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip Module Files
        run:
          zip -r -q PyPyInstaller-${{ github.ref_name }}.zip src/PyPyInstaller
      - name: Create Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.RELEASE_SECRET }}
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
        run:
          gh release upload ${{ github.ref_name }} PyPyInstaller-${{ github.ref_name }}.zip